# Copyright (c) Malong Technologies Co., Ltd.
# All rights reserved.
#
# Contact: github@malong.com
#
# This source code is licensed under the LICENSE file in the root directory of this source tree.

MODEL:
  BACKBONE:
    NAME: resnet50

INPUT:
   MODE: 'RGB'
   PIXEL_MEAN: [0.4620, 0.3980, 0.3292]
   PIXEL_STD: [0.2619, 0.2529, 0.2460]

#  MAX_ITERS: 34677 60 epochs
#  STEPS: [1200, 2400, 4800, 9600, 19200]

#  MAX_ITERS: 17338 30 epochs
#  MAX_ITERS: 5780 10 epochs
SOLVER:
  MAX_ITERS: 5780
  STEPS: [1200, 2400, 4800]
  OPTIMIZER_NAME: Adam
  BASE_LR: 0.00003
  WARMUP_ITERS: 0
  WEIGHT_DECAY: 0.0005

DATA:
  DATASET_NAME: hotelid
  TRAIN_IMG_SOURCE: ../../datasets/hotelid-2021/train.txt
  TEST_IMG_SOURCE: ../../datasets/hotelid-2021/val1.txt
  TRAIN_BATCHSIZE: 80
  TEST_BATCHSIZE: 256
  NUM_WORKERS: 8
  NUM_INSTANCES: 5

VALIDATION:
  VERBOSE: 15000
  TYPES: ['val1.txt', 'val2.txt', 'val3.txt', 'val4.txt']
