# Copyright (c) Malong Technologies Co., Ltd.
# All rights reserved.
#
# Contact: github@malong.com
#
# This source code is licensed under the LICENSE file in the root directory of this source tree.

MODEL:
  BACKBONE:
    NAME: resnet50

INPUT:
   MODE: 'RGB'
   PIXEL_MEAN: [0.5805, 0.5247, 0.4683]
   PIXEL_STD: [0.2508, 0.2580, 0.2701]

SOLVER:
  MAX_ITERS: 220700
  STEPS: [1200, 2400, 4800, 9600, 19200, 38400, 76800, 153600]
  OPTIMIZER_NAME: Adam
  BASE_LR: 0.00003
  WARMUP_ITERS: 0
  WEIGHT_DECAY: 0.0005
  
DATA:
  DATASET_NAME: hotels
  TRAIN_IMG_SOURCE: ../../datasets/hotels50k/train.txt
  TEST_IMG_SOURCE: ../../datasets/hotels50k/val1.txt
  TRAIN_BATCHSIZE: 80
  TEST_BATCHSIZE: 256
  NUM_WORKERS: 8
  NUM_INSTANCES: 5

VALIDATION:
  VERBOSE: 15000
  TYPES: ['val1.txt', 'val2.txt', 'val3.txt', 'val4.txt']
